version: '2'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
    command: mongod --smallfiles

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
